#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-detroit
Version  : 0.4.0
Release  : 3
URL      : https://rubygems.org/downloads/detroit-0.4.0.gem
Source0  : https://rubygems.org/downloads/detroit-0.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: rubygem-detroit-bin
BuildRequires : ruby
BuildRequires : rubygem-detroit-gem
BuildRequires : rubygem-detroit-yard
BuildRequires : rubygem-facets
BuildRequires : rubygem-indexer
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
# Detroit
[Website](http://rubyworks.github.io/detroit) /
[Report Issue](http://github.com/rubyworks/detroit/issues) /
[Development](http://github.com/rubyworks/detroit)

%package bin
Summary: bin components for the rubygem-detroit package.
Group: Binaries

%description bin
bin components for the rubygem-detroit package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n detroit-0.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-detroit.gemspec

%build
gem build rubygem-detroit.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
detroit-0.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/detroit-0.4.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Array/to_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Assembly/cdesc-Assembly.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Assembly/find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Assembly/included-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Assembly/line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Assembly/lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Assembly/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Assembly/register_tool-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/assemble%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/assemble-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/assembly%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/assembly-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/available%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/cdesc-BasicTool.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/initialize_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/metadata-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/prerequisite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/project%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/project-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicTool/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicUtils/apply_naming_policy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicUtils/cdesc-BasicUtils.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicUtils/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicUtils/naming_policy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicUtils/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/BasicUtils/root_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/EmailUtils/cdesc-EmailUtils.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/EmailUtils/email-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/account-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/cdesc-Emailer.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/email-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/environment_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/login-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/mailto-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/new_with_environment-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/passwd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/password-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/require_smtp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/secure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/server-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Emailer/subject-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/cdesc-Project.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/factory-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/lookup-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/metadata-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/root-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Project/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyProject/cdesc-RubyProject.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyProject/gemspec_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyProject/index_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyProject/metadata-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyProject/project%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyUtils/cdesc-RubyUtils.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyUtils/current_platform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/RubyUtils/prerequisite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/absolute%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/append-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/ask-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/atime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/blockdev%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/cdesc-ShellUtils.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/chardev%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/compare_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/ctime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/debug%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/directory%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/dryrun%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/executable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/executable_real%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/exist%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/file%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/fileutils-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/force%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/force-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/grpowned%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/identical%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/initialize_extension_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/initialize_extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/mtime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/multiglob-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/multiglob_r-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/noop%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/owned%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/path%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/pipe%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/prerequisite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/print-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/puts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/quiet%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/quiet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/readable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/readable_real%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/relative%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/report-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/ruby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/safe%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/setgid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/setuid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/sh-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/silent%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/size%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/socket%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/stderr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/stdin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/stdout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/sticky%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/symlink%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/trace%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/trace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/trial%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/trial-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/utime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/verbose%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/verbose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/writable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/writable_real%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/ShellUtils/zero%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Tool/cdesc-Tool.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/application-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/assembly%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/assembly-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/cdesc-CLI.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/execute-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/execute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/force%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/force-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/multitask%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/multitask-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_assembly-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_force-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_loadpath-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_multitask-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_quiet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_toolchain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_trace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_trial-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_verbose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/option_warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/quiet%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/quiet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/toolchains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/trace%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/trace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/trial%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/trial-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/usage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/usage_banner-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/verbose%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/CLI/verbose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/assemblies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/assembly_filenames-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/defaults%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/load_assemblies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/load_assembly_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/load_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/load_plugin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/load_plugins-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Config/workers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/active_workers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/ansize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/assembly%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/assembly-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/cdesc-Runner.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/common_tool_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/config_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/defaults%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/display_action-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/display_help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/header_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/load_plugin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/load_toolchain_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/load_toolchains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/multitask%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/multitask%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/print_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/print_phase-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/printline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/project-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/quiet%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/quiet%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/run_a_worker-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/screen_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/skip%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/status_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/status_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/tool_calls-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/tool_class_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/toolchain_filenames-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/toolchain_files%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/toolchain_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/toolchains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Runner/tools-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/BlockContext/cdesc-BlockContext.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/BlockContext/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/BlockContext/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/BlockContext/set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/BlockContext/settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/CustomContext/cdesc-CustomContext.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/CustomContext/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/CustomContext/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/CustomContext/respond_to%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/CustomContext/settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/ERBContext/__binding__-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/ERBContext/cdesc-ERBContext.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/ERBContext/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/ERBContext/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/ERBContext/project-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/cdesc-Script.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/custom-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/erb-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/initialize_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/project-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/tool-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/tools-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Script/track-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/active%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/active-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/cdesc-Worker.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/invoke-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/priority%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/priority-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/stop%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/tool-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/track%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/Worker/track-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/YAML/cdesc-YAML.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/cdesc-Toolchain.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Toolchain/cli-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/Tools/cdesc-Tools.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/assemblies-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/assembly-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/cdesc-Detroit.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/define_tool_method-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/help%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/metadata-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/project-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/register_tool-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/tool_exec-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Detroit/tools-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/FileTest/bin%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/FileTest/cdesc-FileTest.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/FileTest/command_paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Hash/argumentize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Hash/command_vector-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Hash/to_argv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Hash/to_console-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/NilClass/cdesc-NilClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/NilClass/to_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/Object/to_yamlfrag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/String/to_actual_filename%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/String/to_actual_filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/String/to_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/String/unfold_paragraphs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/page-EXAMPLE_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/detroit-0.4.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/.index
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/EXAMPLE.md
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/bin/detroit
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit.yml
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/assembly.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/basic_tool.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/basic_utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/facets.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/filetest.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/shell_extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/to_actual_filename.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/to_console.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/to_list.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/to_yamlfrag.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/core_ext/unfold_paragraphs.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/email_utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/exec.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/project.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/ruby_utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/shell_utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/toolchain.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/toolchain/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/toolchain/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/toolchain/runner.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/toolchain/script.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/lib/detroit/toolchain/worker.rb
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/man/detroit.1
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/man/detroit.1.html
/usr/lib64/ruby/gems/2.2.0/gems/detroit-0.4.0/man/detroit.1.ronn
/usr/lib64/ruby/gems/2.2.0/specifications/detroit-0.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/detroit
